repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        exclude: 'fixtures/.*\.json$'
      - id: end-of-file-fixer
        exclude: 'fixtures/.*\.json$'
      - id: trailing-whitespace
        exclude: 'fixtures/.*\.json$'
      - id: check-merge-conflict
