[project]
name = "lifestyle_fashion_pro"
authors = [
    { name = "Retail Industry Suite", email = "admin@example.com"}
]
description = "Collections, influencer collaborations, trend boards, lookbooks, loyalty points and style consultations for lifestyle/fashion retail on ERPNext."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
